apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: example.com/external-nfs
parameters:
  server: 192.168.10.20
  path: /data/mydata
  readOnly: "false"
volumeBindingMode: WaitForFirstConsumer
