kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30672
   - name: prometheus
     protocol: TCP
     port: 15692
     nodePort: 32672
  selector:
    app: rabbitmq
